ansible_python_interpreter: /usr/bin/python3

nfs_vhostname: nfs.storage
nfs_vip: 192.168.121.254

ganesha_recovery_pool: cephfs.tank.meta
ganesha_recovery_user: nfsmeta

ganesha_exports:
  - id: 100
    path: /
    pseudo_path: /data
    fs: tank
    user: nfs

ganesha_nodeid: "nfs.storage"

root_authorized_keys: https://github.com/larsks.keys
