- hosts: all
  vars:
    ceph_packages:
      - ceph-common
      - cephadm
  become: true
  tasks:
    - name: install ceph packages
      package:
        name: "{{ ceph_packages }}"
        state: installed
