- hosts: clients
  tags: [clients]
  tasks:
    - name: install packages
      package:
        name: "{{ packages }}"
        state: installed
      vars:
        packages:
          - nfs-utils

    - name: ensure mountpoint exists
      file:
        path: /data
        state: directory

    - name: mount filesystem
      mount:
        src: nfs.storage:/data
        path: /data
        state: mounted
        fstype: nfs
        opts: nfsvers=4,minorversion=2,noauto
