- hosts: clients
  tags: [clients]
  become: true
  tasks:
    - name: install packages
      package:
        name: "{{ packages }}"
        state: installed
      vars:
        packages:
          - nfs-utils

    - name: ensure mountpoint exists
      file:
        path: /data
        state: directory

    - name: mount filesystem
      mount:
        src: "{{ nfs_vhostname }}:/data"
        path: /data
        state: present
        fstype: nfs
        opts: nfsvers=4,minorversion=2
