all:
  vars:
    ansible_user: root
    ansible_python_interpreter: /usr/bin/python3
  children:
    ceph:
      hosts:
        ceph.storage:
      vars:
        virt_extra_disks:
          - size: 20
    nfs:
      hosts:
        nfs1.storage:
        nfs2.storage:
    clients:
      hosts:
        client1.storage:
        client2.storage:
