- hosts: all
  vars:
    vm_action: create
  tasks:
    - when: vm_action == 'create'
      include_role:
        name: virt

    - when: vm_action == 'destroy'
      include_role:
        name: virt
        tasks_from: destroy
