- hosts: nfs
  tags: [keepalived]
  tasks:
    - name: install keepalived
      package:
        name: keepalived
        state: installed

    - name: install keepalived configuration
      template:
        src: keepalived.conf
        dest: /etc/keepalived/keepalived.conf
      notify: restart keepalived
      vars:
        vrrp_state: >-
          {% if inventory_hostname == groups.nfs[0] %}ACTIVE{% else %}BACKUP{% endif %}

    - name: activate keepalived
      service:
        name: keepalived
        state: started
        enabled: true

  handlers:
    - name: restart keepalived
      service:
        name: keepalived
        state: restarted
