- hosts: all
  tags: [hosts]
  gather_facts: true
  roles:
    - etchosts

- hosts: ceph_servers
  tags: [ceph]
  roles:
    - ceph

- hosts: ceph_servers[0]
  tags: [ceph]
  gather_facts: true
  roles:
    - ceph/bootstrap

- hosts: ceph_servers:!ceph_servers[0]
  tags: [ceph]
  roles:
    - ceph/config_ssh

- hosts: ceph_servers[0]
  tags: [ceph]
  roles:
    - ceph/add_hosts

- hosts: ceph_servers[0]
  tags: [ceph]
  become: true
  tasks:
    - name: wait for ceph to discover devices
      command: ceph orch device ls
      register: devices
      until: devices.stdout_lines|length == groups.ceph_servers|length + 1
      retries: 24
      delay: 5
      changed_when: false

    - name: add devices
      command: ceph orch apply osd --all-available-devices

    - name: generate ceph conf
      changed_when: false
      command: ceph config generate-minimal-conf
      register: ceph_conf

    - name: save ceph.conf locally
      delegate_to: localhost
      copy:
        dest: credentials/ceph.conf
        content: |
          {{ ceph_conf.stdout }}

- hosts: nfs_servers
  tags: [nfs, nfs.cluster]
  roles:
    - pacemaker
    - ganesha
