- hosts: ceph_servers
  vars:
    ceph_packages:
      - ceph-common
      - cephadm
  become: true
  tasks:
    - name: install ceph repo
      package:
        name: centos-release-ceph-pacific.noarch
        state: installed

    - name: install ceph packages
      package:
        name: "{{ ceph_packages }}"
        state: installed
