- name: add disks to ceph cluster
  hosts: ceph_servers[0]
  become: true
  tasks:
    - name: wait for ceph to discover devices
      command: ceph orch device ls
      register: devices
      until: devices.stdout_lines|length == groups.ceph_servers|length + 1
      retries: 24
      delay: 5
      changed_when: false

    - name: add devices
      command: ceph orch apply osd --all-available-devices
